# Office Lights Motion Off
#
# If motion is no longer detected and the Office
# is not occupied, turn the lights off quickly.
#
# Enabled by office_lights_motion_on, disables itself after running.
#

automation:
  - id: "office_lights_motion_off"
    initial_state: off
    alias: "Office lights motion off"
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.office_aqara_motion_sensor
        to: "off"
        for:
          minutes: 1
    conditions:
      # Office is not occupied
      - condition: state
        entity_id: input_boolean.office_occupied
        state: "off"
      # Office presence Bayesian sensor is off
      - condition: state
        entity_id: binary_sensor.office_presence
        state: "off"
      # Lights are currently on
      - condition: state
        entity_id: light.office_ceiling_bulbs
        state: "on"
    actions:
      - action: light.turn_off
        target:
          entity_id: light.office_ceiling_bulbs

      # Turn off this automation
      - action: automation.turn_off
        target:
          entity_id: automation.office_lights_motion_off

      # Clear the auto flag
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.office_lights_auto
