# Bedtime Mode Vacation Automations
#
# These automations are toggled by the vacation_mode
# automations.
#
# If we're on vacation/extended away, then we'll turn
# on bedtime mode at 10pm and off at 7am
automation:
  #
  # Turn ON bedtime mode at 10 when we're not home
  #
  - id: "bedtime_mode_vacation_on"
    initial_state: on
    alias: "Bedtime Mode - Vacation On"
    triggers:
      # At 10pm
      - trigger: time
        at: "22:00:00"
    conditions:
      # House is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "off"
      # Only on vacation (initial_state re-enables this on restart)
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - action: input_boolean.turn_on
        entity_id: input_boolean.bedtime

  #
  # Turn OFF bedtime mode at 7am when we're not home
  #
  - id: "bedtime_mode_vacation_off"
    initial_state: on
    alias: "Bedtime Mode - Vacation Off"
    triggers:
      # At 7am
      - trigger: time
        at: "07:00:00"
    conditions:
      # House is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "off"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.bedtime
