- platform: template
  sensors:
    dining_room_presence:
      friendly_name: "Dining Room Presence"
      unique_id: "dining_room_presence"
      value_template: >-
        {{ expand('group.room_presence_devices')|selectattr('state', 'eq', 'dining_room')|map(attribute='name')|list | join(', ') | regex_replace('Room Presence','') }}
