binary_sensor:
  # Upper Floor Motion Group
  #
  - platform: group
    name: Upper Floor Motion
    unique_id: upper_floor_motion
    device_class: motion
    entities:
      - binary_sensor.upstairs_hallway_nightlight_motion
      - binary_sensor.main_bedroom_motion_sensor
      - binary_sensor.main_bathroom_motion_sensor_status

  # Upper Floor Occupancy Group
  #
  - platform: group
    name: Upper Floor Occupancy
    unique_id: upper_floor_occupancy
    device_class: occupancy
    entities:
      - binary_sensor.main_bedroom_motion_sensor_occupancy
      - binary_sensor.main_bathroom_motion_sensor_occupancy

#
# Upper Floor Areas Group
# 
group:
  upper_floor_areas:
    name: Upper Floor Areas
    entities:
      - input_boolean.main_bedroom_occupied
      - input_boolean.main_bathroom_occupied
      - input_boolean.gianlucas_room_occupied
      - input_boolean.ninos_bedroom_occupied
      - input_boolean.upstairs_hallway_occupied

# 
# Upper Floor Sensor
# 
# This is a sensor that's acts like an object with various 
# attributes based on the upper floor areas.
# 
template:
  # Upper Floor Room Presence
  #
  # Binary sensor to reeturn if anybody is detected
  # via BLE presence.
  - binary_sensor:
      - name: "Upper Floor Any Room Presence"
        unique_id: upper_floor_any_room_presence
        default_entity_id: binary_sensor.upper_floor_any_room_presence
        state: >-
          {{
            expand('group.room_presence_devices') |
            selectattr('state', 'in', ['main_bedroom', 'main_bathroom', 'gianlucas_room', 'nino_room', 'upstairs_guest_bedroom']) |
            map(attribute='name') |
            list |
            length > 0
          }}

      # Upper Floor Occupied
      #
      - name: "Upper Floor Occupied"
        unique_id: upper_floor_occupied
        default_entity_id: binary_sensor.upper_floor_occupied
        state: >-
          {{
            states.input_boolean.main_bedroom_occupied.state == "on"
            or states.input_boolean.main_bathroom_occupied.state == "on"
            or states.input_boolean.gianlucas_room_occupied.state == "on"
            or states.input_boolean.ninos_bedroom_occupied.state == "on"
            or states.input_boolean.upstairs_hallway_occupied.state == "on"
          }}

  - sensor:
      - name: "Upper Floor"
        unique_id: upper_floor
        state: "{{ states.binary_sensor.upper_floor_occupied.state }}"
        attributes:
          motion: "{{ states.binary_sensor.upper_floor_motion.state }}"
          occupancy: "{{ states.binary_sensor.upper_floor_occupancy.state }}"
          presence: "{{ states.binary_sensor.upper_floor_any_room_presence.state }}"
          areas: >
            {{ 
              expand('group.upper_floor_areas')
              | map(attribute='entity_id')
              | list
              | join(', ')
            }}
          occupied_rooms: >
            {{ 
              expand('group.upper_floor_areas')
              | selectattr('state', 'eq', 'on')
              | map(attribute='entity_id')
              | list
              | join(', ')
            }}
          occupied_rooms_count: >
            {{ 
              expand('group.upper_floor_areas')
              | selectattr('state', 'eq', 'on')
              | map(attribute='entity_id')
              | list
              | length
            }}
          unoccupied_rooms: >
            {{ 
              expand('group.upper_floor_areas')
              | selectattr('state', 'eq', 'off')
              | map(attribute='entity_id')
              | list
              | join(', ')
            }}
          unoccupied_rooms_count: >
            {{ 
              expand('group.upper_floor_areas')
              | selectattr('state', 'eq', 'off')
              | map(attribute='entity_id')
              | list
              | length
            }}

