# Turn the foyer lights to dim
#
automation:
  - id: "foyer_lights_to_dim"
    initial_state: on
    alias: "Foyer lights to dim"
    trigger:
      # somebody is in bed
      - platform: state
        entity_id: binary_sensor.somebody_in_bed
        to: "on"
    condition:
      # Make sure lighting automations are on
      - condition: state
        entity_id: input_boolean.lighting_automations
        state: "on"
      # Make sure the house is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
      # Chandelier is ON
      - condition: state
        entity_id: light.foyer_chandelier
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.foyer_chandelier
        data:
          brightness_pct: 15
          transition: 0.5
      