# Alarm - Disarm When Somebody Arrives and House Occupied
# 
# This automation will disarm the alarm when somebody arrives and the house is occupied.
# 
automation:
  - id: "alarm_disarm_when_somebody_arrives_and_house_occupied"
    alias: "Alarm - Disarm When Somebody Arrives and House Occupied"
    mode: "single"
    triggers:
      # Somebody Arrives
      # 
      - trigger: state
        entity_id:
          - sensor.john_person
          - sensor.cristina_person
          - sensor.nonna_person
          - sensor.tayta_person
          - sensor.jido_person
          - sensor.katia_person
          - sensor.celi_person
          - sensor.joe_person
          - sensor.alex_person
          - sensor.nonno_person
        from: "not_home"
        to: "home"
    conditions:
      # Alarm is currently armed
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_home"
      # House is occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
      # 
      # Ensure that the person has entry to the house
      # 
      - condition: template
        value_template: >
          {{ state_attr(trigger.entity_id, 'unlock_privilege') == "on" }}
    actions:
      # Disarm the alarm
      # - service: alarm_control_panel.alarm_disarm
      #   entity_id: alarm_control_panel.kohbo
      - action: alarmo.disarm
        entity_id: alarm_control_panel.alarmo
        data:
          code: !secret alarmo_code

      # Reset the inovelli light switch led bar
      - type: issue_all_led_effect
        domain: zha
        device_id: 0526b246502b6d36f56506a277cbab48
        effect_type: Solid
        color: 170
        level: 10
        duration: 255
