automation:
  - id: "alarm_disarm_in_morning"
    alias: "Alarm - Disarm in Morning"
    mode: "single"
    triggers:
      # Bedtime mode disabled for 3 minutes
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "off"
      # House goes from Bedtime to Auto state
      - trigger: state
        entity_id: input_select.house
        from: "Bedtime"
        to: "Auto"
        for: 
          seconds: 15
      # At 6:0s0am
      - trigger: time
        at: "06:00:00"
    conditions:
      # Alarm is currently armed_home
      - condition: state
        # entity_id: alarm_control_panel.kohbo
        entity_id: alarm_control_panel.alarmo
        state: "armed_home"
      # House is currently occupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "on"
      # After 5am
      - condition: time
        after: "05:00:00"
    actions:
      # First floor has been occupied for more than 3 minutes
      - wait_template: >-
          {{
            states.binary_sensor.first_floor_occupancy.state == "on" and
            (as_timestamp(now()) - as_timestamp(states.binary_sensor.first_floor_occupancy.last_changed)) | int >= 30
          }}

        timeout: "01:30:00"
        continue_on_timeout: false

      # Disarm the alarm
      # - action: alarm_control_panel.alarm_disarm
      #   entity_id: alarm_control_panel.kohbo
      - action: alarmo.disarm
        entity_id: alarm_control_panel.alarmo
        data:
          code: !secret alarmo_code

      # Reset the inovelli light switch led bar
      - type: issue_all_led_effect
        domain: zha
        device_id: 0526b246502b6d36f56506a277cbab48
        effect_type: Solid
        color: 170
        level: 10
        duration: 255

      # Notification
      - action: script.general_notification
        data:
          message: Home is now disarmed!
          title: Security System
          devices: "all"
          priority: "active"
          tag: "home-security"
          url: /dashboard-kohbo/security
