# General Notification
#
#
# USAGE:
# action: script.general_notification
# data:
#   title: "Home Assistant"
#   message: "Hello, world!"
#   devices: ["notify.mobile_app_jk_2"] or "all"
#   priority: "active"
#   tag: ""
#   group: "example-notification-group"
#   actions:  # Optional - for actionable notifications
#     - action: "ACTION_ID_1"
#       title: "Action 1"
#     - action: "ACTION_ID_2" 
#       title: "Action 2"
#

#
# Priority options:
# - active: general notification default
# - passive: logging purposes
# - time-sensitive: time sensitive
# - critical: critical iOS alert
#

input_select:
  notification_level:
    name: Notification Level
    options:
      # All priority option levels
      - "All"
      # Only time sensitive and critical
      - "Important"
      # Turn off push notifications
      - "None"

script:
  # 
  # 
  # Clear Notifications
  # 
  clear_notifications:
    alias: "Clear Notifications"
    mode: "queued"
    sequence:
      - action: >
          {% if devices == "all"  %}
            notify.ios_family
          {% elif devices == "jk" %}
            notify.mobile_app_jk_2
          {% elif devices == "cfalb" %}
            notify.mobile_app_cfalb
          {% endif %}
        data:
          message: "clear_notification"
          data:
            tag: "{{ tag }}"

  # 
  # 
  # General Notification
  # 
  general_notification:
    alias: General Notification
    mode: "queued"
    icon: mdi:message-alert

    fields:
      #
      # 
      # Devices
      # 
      devices:
        name: Devices
        description: The devices to send the notification to
        example: "all"
        default: "all"
        required: true
        selector:
          select:
            options:
              - all
              - jk
              - cfalb
      #
      # 
      # Title
      # 
      title:
        name: Title
        description: The title of the push notification
        example: "Home Assistant"
        default: "Home Assistant"
        required: true
        selector:
          text:
            type: text
      #
      # 
      # Message
      # 
      message:
        name: Message
        description: The message of the push notification
        example: "Hello, world!"
        default: "Hello, world!"
        required: true
        selector:
          text:
            type: text
      #
      # 
      # Priority
      # 
      priority:
        name: Priority
        description: The priority of the push notification
        example: "active"
        default: "active"
        selector:
          select:
            options:
              - active
              - passive
              - time-sensitive
              - critical
      #
      # 
      # Tag
      # 
      tag:
        name: Tag
        description: The tag of the push notification
        example: "front_door_person_alert"
        default: "push_1234567890"
        selector:
          text:
            type: text
      #
      # 
      # Image
      # 
      image:
        name: Image
        description: An image to display in the push notification, typically used for camera alerts
        example: "https://example.com/image.png"
        default: "https://example.com/image.png"
        selector:
          text:
            type: text
      #
      # 
      # Entity ID
      # 
      entity_id:
        name: Camera Entity ID
        description: Provide the entity ID of a camera that can be used to stream directly from the notification
        example: "camera.camera_proxy_camera_front_door_camera_high_resolution_channel"
        default: "camera.camera_proxy_camera_front_door_camera_high_resolution_channel"
        selector:
          text:
            type: text
      #
      # 
      # Actions
      # 
      actions:
        name: Actionable Notification Actions
        description: Actions to display in the push notification
        example: "{{ actions }}"
        default: "{{ actions }}"
      # 
      # 
      # URL
      # 
      url:
        name: URL
        description: If provided, the notification will route to this URL
        example: /dashboard-kohbo/home
        default: /dashboard-kohbo/home
        selector:
          text:
            type: text
      
    
    # 
    # Sequence
    # 
    sequence:
      - alias: "Set up variables"
        variables:
          tag: "{{ tag | default('push_' ~ now().timestamp() | int) }}"
          image: "{{ image | default('') }}"
          entity_id: "{{ entity_id | default('') }}"
          url: "{{ url | default('') }}"
          priority: >-
            {% if priority is defined and priority|length %}
              {{priority}}
            {% else %}
              "active"
            {% endif %}

      # Make sure notifications are not disabled
      - condition: template
        value_template: "{{ states.input_select.notification_level.state != 'None' }}"

      - condition: or
        conditions:
          # If notification level is all
          - condition: state
            entity_id: input_select.notification_level
            state: "All"
          # OR important notifications only is enabled and the
          # priority is time sensitive or critical
          - condition: template
            value_template: >-
              {% 
                if states.input_select.notification_level.state == 'Important'
                and (priority == "critical" or priority == "time-sensitive")
              %}
                true
              {% else %}
                false
              {% endif %}

      #
      # Send the push notification
      #
      - action: >
          {% if devices == "all"  %}
            notify.ios_family
          {% elif devices == "jk" %}
            notify.mobile_app_jk_2
          {% elif devices == "cfalb" %}
            notify.mobile_app_cfalb2
          {% endif %}
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          data:
            tag: "{{ tag }}"
            image: "{{ image }}"
            entity_id: "{{ entity_id }}"
            push:
              interruption-level: "{{ priority }}"
            actions: "{{ actions }}"
            url: "{{url}}"
     

automation:
  #
  - id: "notifications_activate_important_only"
    alias: "Notifications - Activate Important Only"
    mode: "single"
    triggers:
      # Bedtime mode is ON
      - trigger: state
        entity_id: input_boolean.bedtime
        to: "on"
      # Entertainment mode is ON
      - trigger: state
        entity_id: input_boolean.entertainment_mode
        to: "on"
      # House is no longer occupied
      - trigger: state
        entity_id: input_boolean.house_occupied
        to: "off"
    condition:
      # Notification level is ALL
      - condition: state
        entity_id: input_select.notification_level
        state: "All"
    action:
      # Set the notification level to "Important"
      - action: input_select.select_option
        data:
          entity_id: input_select.notification_level
          option: "Important"
