# 
# Leak Sensors Group
# 
group:
  leak_sensors:
    name: Leak Sensors
    entities:
      - binary_sensor.kitchen_sink_leak_sensor
      - binary_sensor.laundry_room_leak_sensor
      - binary_sensor.basement_sum_pump_leak_sensor
      - binary_sensor.upstairs_laundry_leak_sensor
      - binary_sensor.storage_room_leak_sensor
      - binary_sensor.basement_exterior_door_leak_sensor
      - binary_sensor.basement_window_leak_sensor_moisture
      - binary_sensor.furnace_pan_leak_sensor_moisture
      - binary_sensor.leak_sensor_hvac_moisture
      - binary_sensor.leak_sensor_basement_bathroom_moisture
      - binary_sensor.main_bathroom_leak_sensor_moisture
      - binary_sensor.nino_s_bathroom_leak_sensor_moisture
      - binary_sensor.upstairs_hallway_bathroom_leak_sensor_moisture


# 
# Leak Sensors Unavailable Sensor
# 
template:
  - sensor:
      - name: "Leak Sensors Unavailable"
        unique_id: leak_sensors_unavailable
        state: >
          {{
            "on" if 
            (
              expand('group.leak_sensors')
              | selectattr('state', 'eq', 'unavailable')
              | list
              | length > 0
            )
            else "off"
          }}
        attributes:
          count: >
            {{
              expand('group.leak_sensors')
              | selectattr('state', 'eq', 'unavailable')
              | list
              | length
            }}
          unavailable_list: >
            {{
              expand('group.leak_sensors')
              | selectattr('state', 'eq', 'unavailable')
              | map(attribute='name')
              | list
              | join(', ')
            }}

  # Binary sensors to track if there is a leak while we're homem or away
  - binary_sensor:
      # Leak while detected while we're away!
      - name: "Leak detected while we are away"
        unique_id: "leak_while_away"
        default_entity_id: binary_sensor.leak_while_away
        state: >-
          {{ is_state('input_boolean.house_occupied','off') and is_state('binary_sensor.leak_sensors','on') }}

      # Leak detected while we're home
      - name: "Leak detected while we are home"
        unique_id: "leak_while_home"
        default_entity_id: binary_sensor.leak_while_home
        state: >-
          {{ is_state('input_boolean.house_occupied','on') and is_state('binary_sensor.leak_sensors','on') }}

# 
# Leak Sensors Binary Sensor
# 
binary_sensor:
  # Group of leak/water sensors
  - platform: group
    name: "Leak Sensors"
    device_class: "moisture"
    entities:
      - binary_sensor.kitchen_sink_leak_sensor
      - binary_sensor.laundry_room_leak_sensor
      - binary_sensor.basement_sum_pump_leak_sensor
      - binary_sensor.upstairs_laundry_leak_sensor
      - binary_sensor.storage_room_leak_sensor
      - binary_sensor.basement_exterior_door_leak_sensor
      - binary_sensor.basement_window_leak_sensor_moisture
      - binary_sensor.furnace_pan_leak_sensor_moisture
      - binary_sensor.leak_sensor_hvac_moisture
      - binary_sensor.leak_sensor_basement_bathroom_moisture
      - binary_sensor.main_bathroom_leak_sensor_moisture
      - binary_sensor.nino_s_bathroom_leak_sensor_moisture
      - binary_sensor.upstairs_hallway_bathroom_leak_sensor_moisture

# Alerts
#
alert:
  # If there's an alert while we're home, we'll send push
  # notification as well as announce around the house.
  water_leak_alert_home:
    name: Water leak alert while home
    entity_id: binary_sensor.leak_while_home
    state: "on"
    repeat:
      - 60
      - 120
      - 180
      - 360
      - 720
    can_acknowledge: True
    skip_first: False
    message: "There is a water leak in the following rooms: {{ expand('binary_sensor.leak_sensors')|selectattr('state', 'eq', 'on')|map(attribute='name')|list|join(', ') }}"
    done_message: "The water leak has been dealt with"
    notifiers:
      - ios_family
      #- tts_announcements_devices
      - leak_voice_announcement

  # If there's a leak while we're away then send us
  # a push notification.
  water_leark_alert_away:
    name: Water leak alert while away
    entity_id: binary_sensor.flood_while_away
    state: "on"
    repeat:
      - 60
      - 120
      - 180
      - 360
      - 720
    can_acknowledge: True
    skip_first: False
    message: "There is a water leak in the following rooms: {{ expand('binary_sensor.leak_sensors')|selectattr('state', 'eq', 'on')|map(attribute='name')|list|join(', ') }}"
    done_message: "The water leak has been dealt with"
    notifiers:
      - ios_family

notify:
  - name: leak_voice_announcement
    platform: rest
    resource: "http://localhost:8123/api/services/script/critical_announcement"
    method: POST_JSON
    headers:
      authorization: !secret restapi_notify
      content-type: "application/json"
    message_param_name: speech_message
    data:
      sound: "nuclear"
      media_players: "auto"
